### ISSUE TITLE
suggestion: activating the github provider

### ISSUE THREAD

**Issue by zackha** [adan-ayaz-stan/conference-app-nuxt#1]
hi @adan-ayaz-stan,

I really like your project. I hope you achieve the success you are aiming for with this project.

When I try to login with my github account for testing purposes, I get the following error.

<img width="322" alt="Capture" src="https://user-images.githubusercontent.com/79358543/225322540-31dc6570-8901-477b-ba8a-53095810d3d8.PNG">

You can solve this problem if you enable github method in this [supabase link](https://app.supabase.com/project/yjhnpxslubsmesevgsnl/auth/providers).

<img width="440" alt="Captures" src="https://user-images.githubusercontent.com/79358543/225323964-0375b8b7-f4b3-41ea-b46d-74f93d23c011.PNG">

I wish you success in your project.

Best Regards;

**Comment by adan-ayaz-stan** [comment]
hey @zackha ,

Yeah actually I didn't added it previously as I had other things in mind when I was building Auth. Now that you've actually mentioned it, I did add the provider so you can now log in and test it out.

A heads up @zackha that the project was actually made to test out the trpc client and how it works. So you are likely to find bugs in it, I think. I made it few months ago so I'm not really sure. I'm glad you like it anyways.

Thank you for your time. Best wishes to you too.

Best Regards;;
